---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/GauravEmani/SampleExample.git
    branch: master
jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: sonarqube,tag: 'latest'}
      inputs:
        - name: resource-tutorial
      run:
          user: root
          path: sh
          args:
          - -exc
          - |
            mvn -f resource-tutorial/pom.xml
            mvn clean install
            mvn test
            mvn package

        