---
resource_types:
  - name: hipchat-notification-resource 
    type: docker-image 
    source: 
       repository: incontact/hipchat-notification-resource 
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/GauravEmani/SampleExample.git
    branch: master

- name: hipchat 
  type: hipchat-notification-resource 
  source: 
     hipchat_server_url: https://api.hipchat.com/v2/room/4062411 
     token: K3FRBBzL3xiwE55yhWLlXshrIPGyk4VXY0ILbm2T t
jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: unit-test
    privileged: true
    file: resource-tutorial/ci/mavenTest/MvnUnitTest.yml
    on_failure:
      do:
      - get: hipchat
      - task: create-notification
        file: resource-tutorial/ci/hipchatNotification/hipchatNotification.yml
    
            

        