---
resource_types:
  - name: hipchat-notification-resource 
    type: docker-image 
    source: 
       repository: incontact/hipchat-notification-resource 
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/GauravEmani/SampleExample.git
    branch: master

- name: hipchat 
  type: hipchat-notification-resource 
  source: 
     hipchat_server_url: https://api.hipchat.com/v2/room/4062411 
     token: K3FRBBzL3xiwE55yhWLlXshrIPGyk4VXY0ILbm2T t
jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: unit-test
    privileged: true
    file: resource-tutorial/ci/mavenTest/MvnUnitTest.yml
    on_failure:
      do:      
      - task: create-notification
        file: resource-tutorial/ci/hipchatNotification/hipchatNotification.yml
      - put: hipchat 
        params: 
          color: red
          from: "Concourse CI" 
          message: 
            template: "${LAST_COMMIT_REPO} \n ${LAST_COMMIT}\n \n. Concourse Job Name :- ${BUILD_JOB_NAME}  \n  <a href='${ATC_EXTERNAL_URL}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}'>Build Logs</a>" 
            params:
             LAST_COMMIT: file://notification-content/notification_body.txt
             LAST_COMMIT_REPO: file://notification-content/notification_repo.txt
  - task: package
    privileged: true
    file: resource-tutorial/ci/mavenTest/MvnPackage.yml
    on_success:
      do:      
      - task: create-notification
        file: resource-tutorial/ci/hipchatNotification/hipchatNotification.yml
      - put: hipchat 
        params: 
          color: green
          from: "Concourse CI" 
          message: 
            template: "${LAST_COMMIT_REPO} \n ${LAST_COMMIT}\n \n. Concourse Job Name :- ${BUILD_JOB_NAME}  \n  <a href='${ATC_EXTERNAL_URL}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}'>Build Logs</a>" 
            params:
             LAST_COMMIT: file://notification-content/notification_body.txt
             LAST_COMMIT_REPO: file://notification-content/notification_repo.txt
            

        